//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityProjeUrunTakipSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBEntityUrunEntities : DbContext
    {
        public DBEntityUrunEntities()
            : base("name=DBEntityUrunEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblKategori> tblKategoris { get; set; }
        public virtual DbSet<tblMusteriler> tblMusterilers { get; set; }
        public virtual DbSet<tblSatislar> tblSatislars { get; set; }
        public virtual DbSet<tblUrunler> tblUrunlers { get; set; }
    }
}
